name: wave_player
description: "A Flutter package for audio waveform visualization and playback with customizable UI components."
version: 0.0.3
homepage: https://github.com/QuangNH0606/wave_player
repository: https://github.com/QuangNH0606/wave_player
issue_tracker: https://github.com/QuangNH0606/wave_player/issues
documentation: https://github.com/QuangNH0606/wave_player#readme
topics:
  - audio
  - waveform
  - music
  - player
  - flutter

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  web:
  macos:

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  http: ^1.5.0
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # Assets for documentation
  assets:
    - assets/

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
